//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULO
    {
        public MODULO()
        {
            this.CONTROL = new HashSet<CONTROL>();
            this.MODULO_PERMISO = new HashSet<MODULO_PERMISO>();
            this.MODULO1 = new HashSet<MODULO>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public string Icono { get; set; }
        public Nullable<int> MODULOPadreId { get; set; }
    
        public virtual ICollection<CONTROL> CONTROL { get; set; }
        public virtual ICollection<MODULO_PERMISO> MODULO_PERMISO { get; set; }
        public virtual ICollection<MODULO> MODULO1 { get; set; }
        public virtual MODULO MODULO2 { get; set; }
    }
}
