//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int Id { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int PRODUCTOId { get; set; }
        public decimal Cantidad { get; set; }
        public int TIPO_MOVIMIENTOId { get; set; }
        public decimal Precio { get; set; }
        public string FolioDocumento { get; set; }
        public string IdDocumento { get; set; }
        public string Entidad { get; set; }
        public int USUARIOIdRealizo { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual TIPO_MOVIMIENTO TIPO_MOVIMIENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
