//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public string CodigoBarras { get; set; }
        public int MARCAId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int ESTADOId { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
