//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CONTROL = new HashSet<CONTROL>();
            this.CONTROL_PERMISO = new HashSet<CONTROL_PERMISO>();
            this.CONTROL_PERMISO1 = new HashSet<CONTROL_PERMISO>();
            this.MODULO_PERMISO = new HashSet<MODULO_PERMISO>();
            this.MODULO_PERMISO1 = new HashSet<MODULO_PERMISO>();
            this.MODULO_PERMISO2 = new HashSet<MODULO_PERMISO>();
        }
    
        public int Id { get; set; }
        public string Alias { get; set; }
        public string Password { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int EMPLEADOId { get; set; }
        public int ROLId { get; set; }
        public int ESTADOId { get; set; }
    
        public virtual ICollection<CONTROL> CONTROL { get; set; }
        public virtual ICollection<CONTROL_PERMISO> CONTROL_PERMISO { get; set; }
        public virtual ICollection<CONTROL_PERMISO> CONTROL_PERMISO1 { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<MODULO_PERMISO> MODULO_PERMISO { get; set; }
        public virtual ICollection<MODULO_PERMISO> MODULO_PERMISO1 { get; set; }
        public virtual ICollection<MODULO_PERMISO> MODULO_PERMISO2 { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
